- name: Assign hostname
  hostname:
    name: "{{ hostname }}"
  when: not (ansible_hostname == hostname)
 
- name: Update & upgrade system
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 86400

- name: Create group for docker
  group:
    name: docker
    state: present

- name: Adding ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
