- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: 1001
    group: 1001
  loop:
    - "{{ app_dir }}"
    - "{{ storage_dir }}"
    - "{{ log_dir }}"

- name: Push Schema Registry deployment files (templates)
  template:
    src: "{{ item }}"
    dest: "{{ app_dir }}/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: ubuntu
    group: ubuntu
  with_fileglob:
    - "{{ app_src }}/*.j2"


- name: Find Schema Registry deployment files (docker-compose)
  become: yes
  find:
    paths: "{{ app_src }}"
    hidden: yes
    use_regex: yes
    patterns: .*\.(yml|yaml)$
  delegate_to: localhost
  register: dc_files

- name: Push Schema Registry deployment files (docker-compose)
  copy:
    src: "{{ item.path }}"
    dest: "{{ app_dir }}"
    owner: ubuntu
    group: ubuntu
  with_items:
    - "{{ dc_files.files }}"

