- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: 1001
    group: 1001
  loop:
    - "{{ app_dir }}"
    - "{{ storage_dir }}"
    - "{{ data_dir }}"
    - "{{ log_dir }}"
    - "{{ build_dir }}/kafka"
    - "{{ build_dir }}/connect"

- name: Push Kafka deployment files
  copy:
    src: "{{ build_kafka_src }}/"
    dest: "{{ build_dir }}/kafka/"
    owner: ubuntu
    group: ubuntu

- name: Push Connect deployment files
  copy:
    src: "{{ build_connect_src }}/"
    dest: "{{ build_dir }}/connect/"
    owner: ubuntu
    group: ubuntu

- name: Push deployment files (templates)
  template:
    src: "{{ item }}"
    dest: "{{ app_dir }}/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: ubuntu
    group: ubuntu
  with_fileglob:
    - "{{ app_src }}/*.j2"

