- hosts: prod
  become: yes
  vars:
    manage_lvm: true
    apps_dir: "/opt"
    data_dir: "/data"
  vars_files:
    - lvm_vars.yml
    - kafka_vars.yml
  roles:
    #- init
    #- mrlesmithjr.manage-lvm
    #- geerlingguy.docker
    - deploy
