- hosts: brokers
  become: yes
  vars:
    manage_lvm: true
    apps_dir: "/opt"
    data_dir: "/data"
    cluster_id: "MjJjNGQyYTE4ZjhiNDczND"
    node_ids: "{{ groups['brokers']
      | map('extract', hostvars, 'node_id')
      | list }}"
    node_ips: "{{ groups['brokers'] 
      | map('extract', hostvars, ['ansible_default_ipv4', 'address'])
      | list }}"
    kafka_controllers: "{{ node_ids
      | zip(node_ips)
      | map('join', '@')
      | join(':9093,') }}:9093"
    docker_daemon_options:
      data-root: '/data/docker'
  vars_files:
    - lvm_vars.yml
    - brokers_vars.yml
  roles:
    - init
    - mrlesmithjr.manage-lvm
    - geerlingguy.docker
    - deploy-kafka
