- hosts: brokers, schema_registry

- hosts: consumer
  become: yes
  vars:
    manage_lvm: true
    apps_dir: "/opt"
    data_dir: "/data"
    docker_data_dir: "/data/docker"
    group_id: "2"
    topic_prefix: "cc"
    kafka_servers: "{{ groups['brokers']
    | map('extract', hostvars, ['ansible_default_ipv4', 'address'])
    | join(':9092,') }}:9092"
    schema_registry: "{{ groups['schema_registry']
    | map('extract', hostvars, ['ansible_default_ipv4', 'address'])
    | join(',') }}"
    docker_daemon_options:
      data-root: '/data/docker'
  vars_files:
    - lvm_vars.yml
    - connect_vars.yml
  roles:
    - init
    - mrlesmithjr.manage-lvm
    - geerlingguy.docker
    - deploy-connect
