lvm_groups:
  - vgname: ebs
    disks:
      - /dev/nvme1n1
    create: true
    lvnames:
      - lvname: data
        size: 8G
        create: true
        filesystem: ext4
        mount: true
        mntp: "{{ data_dir }}"
      - lvname: opt
        size: 100%FREE
        create: true
        filesystem: ext4
        mount: true
        mntp: "{{ apps_dir }}"
